esphome:
  name: poele

esp32:
  board: esp32dev

# Enable logging
logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

http_request:
  verify_ssl: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "poele"
    password: "52705270"

mdns:

web_server:
  port: 80

one_wire:
  - platform: gpio
    pin: GPIO25

spi:
  miso_pin: GPIO19
  clk_pin: GPIO18

sensor:
  - platform: max6675
    name: "Température foyer"
    cs_pin: GPIO5
    update_interval: 60s # Augmentation de l'intervalle pour réduire la consommation
  - platform: dallas_temp
    name: "temperature"
    update_interval: 60s # Augmentation de l'intervalle pour réduire la consommation

deep_sleep:
  id: deep_sleep_mode
  run_duration: 60s # ESP32 stays awake for 1 minute after each restart
  sleep_duration: 3600s # ESP32 sleeps for 1 hour
