esphome:
  name: escalier-haut

esp8266:
  board: d1_wroom_02

# Enable logging
logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password
http_request:
  verify_ssl: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
    name: "PIR Sensor"
    device_class: motion
    filters:
      - delayed_off: 3s

web_server:
  port: 80
