esphome:
  name: goouuu-dallas
  friendly_name: "Goouuu dallas"

esp8266:
  board: d1_wroom_02

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

http_request:
  verify_ssl: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

one_wire:
  - platform: gpio
    pin: GPIO0

sensor:
  - platform: dallas_temp
    name: temperature
    update_interval: 5min

deep_sleep:
  id: deep_sleep_mode
  run_duration: 60s # ESP32 stays awake for 1 minute after each restart
  sleep_duration: 3600s # ESP32 sleeps for 1 hour
