esphome:
  name: dallas

esp8266:
  board: d1_wroom_02

# Enable logging
logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password
http_request:
  verify_ssl: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Escalier-Haut "
    password: "nc2BznQpkele"

mdns:

web_server:
  port: 80

one_wire:
  - platform: gpio
    pin: GPIO0

sensor:
  - platform: dallas_temp
    name: temperature
    update_interval: 5s
