esphome:
  name: escalier-haut-nodemcu-pir

esp8266:
  board: nodemcu

# Enable logging
logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password
http_request:
  verify_ssl: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Escalier-Haut "
    password: "nc2BznQpkele"

binary_sensor:
  - platform: gpio
    pin:
      inverted: true
      number: D2
    name: "PIR Sensor"
    device_class: motion
    filters:
      - delayed_off: 3s

mdns:

web_server:
  port: 80
